params:
  epochs: 4
  no_classes : 10
  batch_size : 32
  loss_function : sparse_categorical_crossentropy # No need to put quotes,they'll be automatically inserted
  optimizer : SGD
  metrics : accuracy
  validation_datasize : 5000
  patience: 2
  restore_best_weights: True
  save_best_only: True


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plot_dir: plots
  model_name: Digit_classifier
  plot_name: Track_performance
  checkpoint_dir: model_checkpoint


logs:
  log_dir: log_dir
  general_logs : general_logs
  tensorboard_logs : tensorboard_logs

