params:
  epochs: 4
  no_classes : 10
  batch_size : 32
  loss_function : sparse_categorical_crossentropy # No need to put quotes,they'll be automatically inserted
  optimizer : SGD
  metrics : accuracy
  validation_datasize : 5000


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plot_dir: plots
  checkpoint_dir : checkpoint
  model_name: Digit_classifier
  plot_name: Track_performance


logs:
  log_dir: log_dir
  general_logs : general_logs
  tensorboard_logs : tensorboard_logs

